package uz.asz.myapp.telegram;

public enum StepEnums {
    BEGIN,
    REGISTER,
    MAIN,
    REGISTER_FIO,
    REGISTER_PHONE_NUMBER,
    REGISTER_FOR_TEACHING_3,
    REGISTER_FOR_TEACHING_4,
    REGISTER_FOR_TEACHING_5,
    SAVE_CONTACT,
    SUCCESSFULLY_REGISTRATED,
}
