package uz.asz.myapp.telegram;

public enum StepEnums {
    BEGIN,
    REGISTER,
    MAIN,
    REGISTER_FOR_TEACHING_1,
    REGISTER_FOR_TEACHING_2,
    REGISTER_FOR_TEACHING_3,
    REGISTER_FOR_TEACHING_4,
    REGISTER_FOR_TEACHING_5,
    SAVE_CONTACT,
    SUCCESSFULLY_REGISTRATED,
}
